### PR TITLE
[KEYCLOAK-4865] keycloak-connect stuck in redirect loop when access token is invalid

### PR DESCRIPTION
**Pull request by abstractj**
In order to see the fix you need: https://github.com/keycloak/keycloak-nodejs-connect/pull/79

@vmuzikar @sebastienblanc could you please review?

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:+1:

**Comment by vmuzikar** [comment]
Seems fine to me.
However, imho it would be a good idea to have a true (non-mocked) HTTPS test as we have with Java adapters. What do you think? Should we create a JIRA for this so we don't forget?
The complication is it would require some configuration of Keycloak as well, i.e. changes in start-`server.sh`.

**Comment by abstractj** [comment]
@vmuzikar would like to have specific tests for HTTPS scenarios? If yes, correct if I'm wrong, but I don't think this is related with this change. But yes, +1 for testing such scenarios, we should support the same scenarios present into the Java adapter.

**Comment by vmuzikar** [comment]
@abstractj Yes, that's just something for future development. Agree, it's not much related to this change - it just came to my mind when I saw that you are adding a HTTPS test with this PR. So, it is a bit related to this change after all. ;)
Should we create a JIRA for future HTTPS tests?

**Comment by abstractj** [comment]
@vmuzikar  +1000

**Pull request merged**
