### PR TITLE
Added note on using semistandard.

### PR DESCRIPTION
**Pull request by thomasdarimont**

### CODE REVIEW

**Comment by helio-frota** [comment]
we have line of doc about semistandard:
https://github.com/keycloak/keycloak-nodejs-auth-utils/blob/master/CONTRIBUTING.md
but I understand this PR as kind of feedback

LGTM

**Comment by thomasdarimont** [comment]
Ah funny - really didn't see that at all.

**Comment by helio-frota** [comment]
@thomasdarimont but this your note is more easy to see than this simple phrase
"Make sure the jshint and semistandard are happy and that all tests pass"

**Comment by lance** [comment]
Thanks for the contrib

**Pull request merged**
