### PR TITLE
grant-manager: replaced this.reject with Promise.reject

### PR DESCRIPTION
**Pull request by akshatcm**
this.reject being undefined, would always throw a TypeError

### CODE REVIEW

**Comment by abstractj** [comment]
@akshatcm  could you please attach a test case scenario for this?

**Comment by akshatcm** [comment]
There is no direct test case scenario for this, as the error is getting internally nullified into a generic error, which says 'validate access token went wrong'.

While I was integrating keycloak into my NodeJs project, I got this error message. On debugging further, I found that its coming from [this](https://github.com/keycloak/keycloak-nodejs-auth-utils/blob/master/lib/grant-manager.js#L241) line. Later I changed this line to:

` }, (err) => { console.log('validate access token went wrong', err && err.stack); })`

To find out the reason why the Promise is getting rejected.

This is when I found the Bug. The error was a TypeError, which said 'TypeError: this.reject is not a function'.

you can try out the same steps yourself. But its pretty obvious that there is a definite TypeError there.

**Comment by abstractj** [comment]
Today all the tests run against the Keycloak server, even being something obvious like you mentioned, we have to make sure that such issue will not repeat again.

**Comment by abstractj** [comment]
@akshatcm landed, I tested it and it works. Thanks for your contribution.

**Pull request merged**
