### PR TITLE
update promise logic in grantManager validateToken/validateGrant

### PR DESCRIPTION
**Pull request by njs50**
to make return result more consistent esp when validation fails.

this fixes a somewhat critical bug.

### CODE REVIEW

**Comment by annie-amplify** [comment]
Thank you! This is a more thorough sweep of the changes needed to fix the security bug for invalid realm keys. The promise rejections were allowing access without a valid token and were throwing test warnings.

**Comment by stianst** [comment]
@annie-amplify does this cover your fixes from https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/48? If so can you close that issue please?

**Comment by stianst** [comment]
Please create a JIRA for this

**Comment by abstractj** [comment]
@njs50 landed, thank you

**Comment by annie-amplify** [comment]
Thanks @abstractj and @njs50

**Comment by njs50** [comment]
perfect, thanks :-)

**Pull request merged**
