### PR TITLE
KEYCLOAK-3419 Add support for env variable references in Config.

### PR DESCRIPTION
**Pull request by thomasdarimont**
Users can now refer to environment variables via ${env.MY_ENV_VAR}.
Optionally users can specify default values that should be returned
if the environment variable is not. E.g. ${env.NOT_SET:fallback}
will yield 'fallback' in case the environment variable 'NOT_SET'
is not configured.

This allows for generic configuration files.

Signed-off-by: Thomas Darimont <thomas.darimont@gmail.com>

### CODE REVIEW

**Comment by abstractj** [comment]
@sebastienblanc would you like to give it a try?

**Comment by helio-frota** [comment]
@thomasdarimont Hi

Thanks for the PR, but the build is broken with semistandard.
After semistandard verification and the tests, it was broken with 'npm run docs' but this was fixed.
Can you please fix the code to adapt to semistandard ?

**Comment by thomasdarimont** [comment]
Amended commit with fixed semistandard complaints.

**Comment by thomasdarimont** [comment]
Hmmm, CI build seems to fail - but I don't see why... it's running file locally (on linux)
```
tom@euler ~/dev/repos/gh/thomasdarimont/keycloak-dev/keycloak-nodejs-auth-utils (issue/KEYCLOAK-3419-support-env-variables-in-config) 
$ node test/unit/config-test.js
TAP version 13
# Config#configure
ok 1 should be equal
# Config#configure with boolean
ok 2 should be equal
# Config#configure with env variable reference not set
ok 3 should be equal
# Config#configure with env variable reference not set with fallback
ok 4 should be equal
# Config#configure with env variable reference set
ok 5 should be equal
# Config#configure with env variable reference set with fallback
ok 6 should be equal

1..6
# tests 6
# pass  6

# ok
```

**Comment by helio-frota** [comment]
@thomasdarimont Are you using nodejs 4x ?

**Comment by thomasdarimont** [comment]
Nope 
```
$ node -v
v6.2.2
```
Perhaphs the "other" 2 machines really don't have the USER env variable set?

**Comment by helio-frota** [comment]
Ok now is bit weird CI is working with 4x.
I'm going to run you PR locally to check too.

**Comment by thomasdarimont** [comment]
I could also try adding:
```
env:
  global:
    - USER: ci
```
to the .travis.yml

**Comment by thomasdarimont** [comment]
Ah that's it :)

**Comment by helio-frota** [comment]
@thomasdarimont good catch !

**Comment by lance** [comment]
LGTM

**Comment by abstractj** [comment]
@thomasdarimont landed here https://github.com/keycloak/keycloak-nodejs-auth-utils/commit/59002162dc641d6a63299c45549b2d279e4ca7a2. Thank you

**Pull request closed without merging**
