### PR TITLE
fixed param naming in token request

### PR DESCRIPTION
**Pull request by rckrdstrgrd**

### CODE REVIEW

**Comment by helio-frota** [comment]
The travis-ci error is a problem with npmjs
https://github.com/npm/npm/issues/13284

**Comment by lance** [comment]
I've kicked off a new CI run....

**Comment by lance** [comment]
@rckrdstrgrd thanks for the contribution. Can you point to some documentation or other reference to illustrate why this change is required?

**Comment by rckrdstrgrd** [comment]
@lance I created an issue, https://issues.jboss.org/browse/KEYCLOAK-3271 . When I run the current release which uses "application_session_state" as request param, the k_logout endpoint will not be invoked by the keycloak server. When using "client_session_state", remote logout works as excepted. 

Maybe I missed some config or something. If so, please ignore this PR.

**Pull request merged**
