### PR TITLE
Handle errors when unable to connect to the Keycloak server

### PR DESCRIPTION
**Pull request by cmacq2**
Fixes: JIRA #KEYCLOAK-4432

See also: https://issues.jboss.org/browse/KEYCLOAK-4432

### CODE REVIEW

**Comment by helio-frota** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:8080`
@abstractj better to start CI build again to be sure this is not CI problem ?

**Comment by cmacq2** [comment]
Related: the stack trace points to the same (structural) problem in `fetch` of `lib/grant-manager.js`.
Again: a Promise is being constructed from a NodeJS HTTP/HTTPS request but no error handling is installed on the request object so... if things fail early, they fail badly.

**Comment by cmacq2** [comment]
Also: CI fails because:
```
--2017-02-15 21:55:58--  http://downloads.jboss.org/keycloak//keycloak-.tar.gz
Resolving downloads.jboss.org (downloads.jboss.org)... 23.61.168.48
Connecting to downloads.jboss.org (downloads.jboss.org)|23.61.168.48|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-15 21:56:02 ERROR 404: Not Found.
tar (child): keycloak-.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Either keycloak vanished from the download server, or it's the extra `/` that's killing CI here.

**Comment by helio-frota** [comment]
yup, because this I was talking about restart the build.

**Comment by cmacq2** [comment]
I noticed a third instance where the same type of fix should apply.
Note that the various unit/integration tests assume Promises always `resolve()` successfully, there are no checks to fail the test on rejection which means the tests will time out instead (if the promises fail).

**Comment by abstractj** [comment]
Landed here https://github.com/keycloak/keycloak-nodejs-auth-utils/commit/a29a9d66dfdbcadd125d35e2a827373959bcfc6e

**Pull request closed without merging**
