### PR TITLE
fix missing callback for validateAccessToken (again)

### PR DESCRIPTION
**Pull request by DorianRohr**
Somehow the fix from KEYCLOAK-3891 vanished in version 3.0.0-Final (and in master branch).

The callback should now be called correctly, if there is one provided.

### CODE REVIEW

**Comment by abstractj** [comment]
@DorianRohr please add functional tests for this change.

**Comment by DorianRohr** [comment]
I have added a test to ensure, that a callback is called, if there is one provided (and that the result is the access_token, that was provided)

**Comment by abstractj** [comment]
@DorianRohr I will look at this next week, sorry about the delay.

**Comment by abstractj** [comment]
@DorianRohr I just rebased it here https://github.com/keycloak/keycloak-nodejs-auth-utils/pull/68. Will merge in a bit.

**Pull request closed without merging**
