### PR TITLE
test expired token and other are kept

### PR DESCRIPTION
**Pull request by sebastienblanc**
@abstractj small addition but tests an important case

### CODE REVIEW

**Comment by abstractj** [comment]
@sebastienblanc seens like you forgot to rebase, maybe?

**Comment by sebastienblanc** [comment]
Indeed, sorry, should be good now

**Comment by abstractj** [comment]
@sebastienblanc looks like travis is unhappy. I think this has to do with code formatting.

**Comment by sebastienblanc** [comment]
no , I completly messed up with the rebase, sorry need to wake up, hold on
for now

**Pull request merged**
